### PR TITLE
Update to Dart 2.0 🎉

### PR DESCRIPTION
**Pull request by leerob**
- Ran [over_react_codemod](https://github.com/Workiva/over_react_codemod) on the codebase
- Updated versions in the `pubspec.yaml` and got `pub get` to run successfully
- Updated the components pulled from the `over_react` examples
- Updated documentation

Hopefully you guys (@evanweible-wf @corwinsheahan-wf and crew) can use this as an example for people migrating as you roll out Dart 2 support. I've been monitoring analytics on my blog post ([here](https://leerob.io/blog/getting-started-with-dart-and-react/)) that uses this tutorial and it's still getting ~100 views per week, as well as ranking on Google when you search "Dart React", so I'm hoping to get this updated so it's accurately promoting Workiva OSS.

### CODE REVIEW

**Comment by evanweible-wf** [comment]
@leerob I think this should take care of the build failure you're seeing: https://github.com/leerob/dart-react-todo/pull/4

**Comment by leerob** [comment]
That worked! I'm able to run locally now 🎉



I'll work on getting the documentation/blog post updated.

**Comment by leerob** [comment]
Hmmm. Running `pub run build_runner test` locally does not work. `ddev test` also doesn't work. Is there further configuration needed for either of those? I'm surprised it works on Travis but not locally. 

Should I be recommending using `build_runner test` for now, or `ddev test`? @evanweible-wf 

I've got the docs mostly updated now, should be almost ready.

**Comment by corwinsheahan-wf** [comment]
@leerob Looks like your `dev.dart` file is set up correctly. I didn't have any issue running tests via `ddev test`. What's the error you're seeing?

**Comment by evanweible-wf** [comment]
@leerob `pub run build_runner test` works for me locally on the latest commit. It's possible that that your `.dart_tool/build/` directory got in a bad state from the failed build you were encountering earlier, could you try removing that directory and then running a build/tests again?

I think recommending `build_runner test` in this project makes the most sense. At this point `ddev test` isn't doing a whole lot and running `build_runner test` will probably become more common on Dart 2 so it'd be good to make people familiar.

**Comment by leerob** [comment]
@evanweible-wf @corwinsheahan-wf Yep, that appeared to be the issue. Blowing away `.dart_tool` fixed the issue and `pub run build_runner test` ran successfully. 

Maybe I can swing back and update this to use `ddev test` in the future, since the `-n` is helpful as projects scale.

**Comment by leerob** [comment]
Woohoo! 🎉 The blog post has been updated (https://github.com/leerob/leerob.io/pull/6) and is live [here](https://leerob.io/blog/getting-started-with-dart-and-react). 

I'll probably post it to `/r/dartlang` to try and get some eyes on OverReact 2.0 when it's released (https://github.com/Workiva/over_react/pull/240).

**Comment by evanweible-wf** [comment]
> Maybe I can swing back and update this to use `ddev test` in the future, since the `-n` is helpful as projects scale.

That's actually a feature of the `test` package itself, ddev test just proxies the flag. You can pass whatever flags you'd like to the underlying test runner like so:

```
pub run build_runner test -- -n 'pattern'
```

And thanks, much appreciated! 2.0 should be published tonight or tomorrow morning.

**Pull request merged**
